In [2]:
import numpy as np

# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a.shape)

# 2D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)


[1 2 3 4 5]
(5,)
(2, 3)


In [3]:
# 1D array with values from 0 to 11
c = np.arange(12)

c2 = c.reshape((3, 4))

# Print the new shape and array
print(c2.shape)
print(c2)


(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
# Access a single element from the 2D array
print(c2[1, 2])

# Extract an entire row and column
row0 = c2[0, :]
col2 = c2[:, 2]
print(row0)
print(col2)

# Use boolean indexing to filter even numbers
mask = c2 % 2 == 0
even = c2[mask]
print(even)


6
[0 1 2 3]
[ 2  6 10]
[ 0  2  4  6  8 10]


In [5]:
# Create a 2D array
d = np.array([[1, 2, 3],
              [4, 5, 6]])

# Multiply every element by 2
print(d * 2)

# Broadcasting
print(d + np.array([10, 20, 30]))

# Perform matrix multiplication with the transpose
mat = d.dot(d.T)
print(mat)


[[ 2  4  6]
 [ 8 10 12]]
[[11 22 33]
 [14 25 36]]
[[14 32]
 [32 77]]


In [6]:
# Aggregates and Axis Operations
print(np.sum(d))
print(np.mean(d, axis=0))
print(np.std(d, axis=1))


21
[2.5 3.5 4.5]
[0.81649658 0.81649658]
